### ISSUE TITLE
Make a starter-kit out of your tasks

### ISSUE THREAD

**Issue by notetiene** [dreamyguy/sidhree-com#3]
I was wondering if you thought about making a starter-kit (or project template whatever we call it) out of your tasks. I see that they look almost the same between your project and I like the way it's done (seriously).

I've been incorporating some of them in my projects (not available yet) and so far I like it.

**Comment by dreamyguy** [comment]
Better late than never!

Yes, back in the day I used the same sort of setup in several projects, but ended up doing slightly different variations according to need, so I never put time making a definite, configurable template system.

I have done some of those more recently, though their purposes are not self-evident:

**Create Some App** https://github.com/dreamyguy/create-some-app
A configurable CLI-based scaffolder that creates some app. That's a pretty recent project I'm pouring a lot of energy on to get right... It's very usable and one can integrate whatever template one creates and adds to it. 🙂 

**Validate Color** https://github.com/dreamyguy/validate-color
Is a fine template for those wanting to publish `npm` packages with a CRA-based GitHub Page as demo. The package and the demo live their own separate lives.

**VanillaJS Starter** https://github.com/dreamyguy/vanillajs-starter
Bare minimum sandbox to get you started with Vanilla JS prototyping in a browser environment.
